name: loomi_challenge
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  custom_pop_up_menu: ^1.2.4
  dio: ^5.4.3+1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_picker: 8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.4
  flutter_bloc: ^8.1.5
  flutter_mobx: ^2.2.1+1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_it: ^7.6.7
  google_fonts: ^5.1.0
  google_sign_in: ^6.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.0.8
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  retrofit: ^4.1.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  video_player: ^2.8.6
  wakelock_plus: ^1.2.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flavorizr:
  flavors:
    dev: 
      app:
        name: "Loomi Challenge Dev"
      android:
        applicationId: "com.loomi.challenge.dev"
      ios:
        bundleId: "com.loomi.challenge.dev"
    homo:
      app:
        name: "Loomi Challenge Homo"
      android:
        applicationId: "com.loomi.challenge.homo"
      ios:
        bundleId: "com.loomi.challenge.homo"
    prod: 
      app:
        name: "Loomi Challenge"
      android:
        applicationId: "com.loomi.challenge"
      ios:
        bundleId: "com.loomi.challenge"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: epilogue
      fonts:
        - asset: assets/fonts/epilogue/Epilogue-Thin.ttf
          weight: 100
        - asset: assets/fonts/epilogue/Epilogue-Light.ttf
          weight: 300
        - asset: assets/fonts/epilogue/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/epilogue/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/fonts/epilogue/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/epilogue/Epilogue-Bold.ttf
          weight: 700
        - asset: assets/fonts/epilogue/Epilogue-ExtraBold.ttf
          weight: 800          
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit\Outfit-Medium.ttf
          weight: 500
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
