name: loomi_challenge
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.1.17
  file_picker: 8.0.0+1
  firebase_core: ^2.27.0
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.6.7
  google_fonts: ^5.1.0
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3

flavorizr:
  flavors:
    dev: 
      app:
        name: "Loomi Challenge Dev"
      android:
        applicationId: "com.loomi.challenge.dev"
      ios:
        bundleId: "com.loomi.challenge.dev"
    homo:
      app:
        name: "Loomi Challenge Homo"
      android:
        applicationId: "com.loomi.challenge.homo"
      ios:
        bundleId: "com.loomi.challenge.homo"
    prod: 
      app:
        name: "Loomi Challenge"
      android:
        applicationId: "com.loomi.challenge"
      ios:
        bundleId: "com.loomi.challenge"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
