name: loomi_challenge
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  custom_pop_up_menu: ^1.2.4
  email_validator: ^2.1.17
  file_picker: 8.0.0+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.4
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_it: ^7.6.7
  google_fonts: ^5.1.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.8
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0

  


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flavorizr:
  flavors:
    dev: 
      app:
        name: "Loomi Challenge Dev"
      android:
        applicationId: "com.loomi.challenge.dev"
      ios:
        bundleId: "com.loomi.challenge.dev"
    homo:
      app:
        name: "Loomi Challenge Homo"
      android:
        applicationId: "com.loomi.challenge.homo"
      ios:
        bundleId: "com.loomi.challenge.homo"
    prod: 
      app:
        name: "Loomi Challenge"
      android:
        applicationId: "com.loomi.challenge"
      ios:
        bundleId: "com.loomi.challenge"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
