// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:loomi_challenge/flavors/flavors.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    print('Current App Environment: ${FlavorSettings.appFlavor}');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FlavorSettings.appFlavor == Flavor.prod
            ? androidProd
            : androidHomoDev;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for IOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyBmsWgLjdWiTJmX4w6wt1u7BFGXV9kE3YM',
    appId: '1:244827145294:android:fba9aa71083b2176c5ef1f',
    messagingSenderId: '244827145294',
    projectId: 'loomi-challenge',
    storageBucket: 'loomi-challenge.appspot.com',
  );

  static const FirebaseOptions androidHomoDev = FirebaseOptions(
    apiKey: 'AIzaSyAREtMUCx6c3TVW79_8_qp4OFVD2Kgw2m4',
    appId: '1:330600322380:android:867dc1166a38ae13d7abe9',
    messagingSenderId: '330600322380',
    projectId: 'loomi-challenge-homo',
    storageBucket: 'loomi-challenge-homo.appspot.com',
  );
}
